services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: 'no'
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgAdmin (Web UI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: 'no'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
