import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import typedocSidebar from './docs/api/typedoc-sidebar';
// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	docsSidebar: [
		{
			type: 'doc',
			id: 'README',
			label: 'Home'
		},
		{
			type: 'category',
			label: 'Getting Started',
			collapsible: false,
			items: [{ type: 'autogenerated', dirName: 'getting-started' }]
		},
		{
			type: 'category',
			label: 'Core Concepts',
			collapsible: false,

			items: [{ type: 'autogenerated', dirName: 'core-concepts' }]
		},
		{
			type: 'category',
			label: 'API Docs',
			collapsible: false,
			link: {
				type: 'doc',
				id: 'api/index'
			},
			items: typedocSidebar.items
		}
	]
};

export default sidebars;
